/*
 * This file is part of the FZPWUploader
 *
 * Copyright (C) 2009 achterblog.de
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package de.achterblog.fzpwuploader.ui;

import de.achterblog.util.Streams;
import java.io.IOException;
import javax.swing.JDialog;

/**
 * An ugly AboutBox
 *
 * @author boris
 */
public class AboutBox extends JDialog {
  /** Creates new form AboutBox */
  public AboutBox(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    copyrightLabel = new javax.swing.JLabel();
    apacheNoticeLabel = new javax.swing.JLabel();
    qosNoticeLabel = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    licenseTextArea = new javax.swing.JTextArea();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    bundledLicensesTextArea = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("About");
    setResizable(false);
    getContentPane().setLayout(new java.awt.GridLayout());

    jPanel1.setLayout(new java.awt.GridBagLayout());

    javaLabel.setText("Running Java " + System.getProperty("java.version") + " by " + System.getProperty("java.vendor"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(javaLabel, gridBagConstraints);

    osLabel.setText("System: " + System.getProperty("os.name") + " " + System.getProperty("os.version") + " running on " + System.getProperty("os.arch"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(osLabel, gridBagConstraints);

    copyrightLabel.setText("<html>© 2009 achterblog.de<br>This tool is published under the terms of the GPLv2 or later.<br>See tabs \"License\" and \"Bundled Licenses\" for details.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(copyrightLabel, gridBagConstraints);

    apacheNoticeLabel.setText("<html>This product includes software developed by<br>The Apache Software Foundation (http://www.apache.org/).");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(apacheNoticeLabel, gridBagConstraints);

    qosNoticeLabel.setText("<html>This product includes software developed by qos.ch<br>which is Copyright (c) 2004-2008 QOS.ch  All rights reserved.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(qosNoticeLabel, gridBagConstraints);

    jLabel1.setText("<html>This product includes software developed by Sun Microsystems<br>which is Copyright (c) 2005 Sun Microsystems, Inc.<br>and kindly was licensed under the terms of the LGPL");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jLabel1, gridBagConstraints);

    jTabbedPane1.addTab("General", jPanel1);

    jPanel2.setLayout(new java.awt.GridLayout());

    licenseTextArea.setColumns(20);
    licenseTextArea.setEditable(false);
    licenseTextArea.setLineWrap(true);
    licenseTextArea.setRows(5);
    licenseTextArea.setText(getLicenseText());
    jScrollPane1.setViewportView(licenseTextArea);

    jPanel2.add(jScrollPane1);

    jTabbedPane1.addTab("License", jPanel2);

    jPanel3.setLayout(new java.awt.GridLayout());

    bundledLicensesTextArea.setColumns(20);
    bundledLicensesTextArea.setRows(5);
    bundledLicensesTextArea.setText(getBundledLicensesText());
    jScrollPane2.setViewportView(bundledLicensesTextArea);

    jPanel3.add(jScrollPane2);

    jTabbedPane1.addTab("Bundled Licenses", jPanel3);

    getContentPane().add(jTabbedPane1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        AboutBox dialog = new AboutBox(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  private String getLicenseText() {
    try {
      return Streams.toString(AboutBox.class.getResourceAsStream("/COPYING"), "US-ASCII");
    } catch (IOException e) {
      return "Could not read License. Visit http://www.gnu.org/licenses/old-licenses/gpl-2.0.html";
    }
  }

  private String getBundledLicensesText() {
    try {
      final String LINE = "\n---------------------------------------\n";
      Class<?> clazz = AboutBox.class;
      StringBuilder b = new StringBuilder();
      b.append(Streams.toString(clazz.getResourceAsStream("/bundled-licenses.txt"), "US-ASCII"));
      b.append(LINE).append("Full text of the Apache 2.0 license follows\n").append(LINE);
      b.append(Streams.toString(clazz.getResourceAsStream("/apache-2.0.txt"), "US-ASCII"));
      b.append(LINE).append("Full text of the LGPL 2.1 follows\n").append(LINE);
      b.append(Streams.toString(clazz.getResourceAsStream("/lgpl-2.1.txt"), "US-ASCII"));
      return b.toString();
    } catch (IOException e) {
      return "Could not read bundled licenses. Perhaps this package does not contain any?";
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel apacheNoticeLabel;
  private javax.swing.JTextArea bundledLicensesTextArea;
  private javax.swing.JLabel copyrightLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTabbedPane jTabbedPane1;
  private final javax.swing.JLabel javaLabel = new javax.swing.JLabel();
  private javax.swing.JTextArea licenseTextArea;
  private final javax.swing.JLabel osLabel = new javax.swing.JLabel();
  private javax.swing.JLabel qosNoticeLabel;
  // End of variables declaration//GEN-END:variables
}
