/*
 * This file is part of the FZPWUploader
 *
 * Copyright (C) 2009-2014 achterblog.de
 *
 * FZPWUploader is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * FZPWUploader is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FZPWUploader.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.achterblog.fzpwuploader.ui;

import de.achterblog.fzpwuploader.UploadBatch;
import de.achterblog.fzpwuploader.UploadBatch.UploadBatchCallback;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author boris
 */
public class Uploader extends javax.swing.JFrame {
  private static final Logger logger = LoggerFactory.getLogger(Uploader.class);

  /** Creates new form Uploader */
  public Uploader() {
    initComponents();

    progressBar.setValue(0);
    activityProgressBar.setVisible(false);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    lableUser = new javax.swing.JLabel();
    labelPassword = new javax.swing.JLabel();
    buttonSelect = new javax.swing.JButton();
    buttonUpload = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    activityProgressBar = new javax.swing.JProgressBar();
    menuBar = new javax.swing.JMenuBar();
    menuFile = new javax.swing.JMenu();
    menuItemExit = new javax.swing.JMenuItem();
    menuQuestionMark = new javax.swing.JMenu();
    menuItemLog = new javax.swing.JMenuItem();
    menuItemAbout = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Uploader");

    fileList.setModel(FileListModel.EMPTY_MODEL);
    jScrollPane1.setViewportView(fileList);

    lableUser.setLabelFor(textFieldUsername);
    lableUser.setText("User:");

    labelPassword.setLabelFor(textFieldPassword);
    labelPassword.setText("Password:");

    progressBar.setStringPainted(true);

    buttonSelect.setText("Select...");
    buttonSelect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonSelectActionPerformed(evt);
      }
    });

    buttonUpload.setText("Upload");
    buttonUpload.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonUploadActionPerformed(evt);
      }
    });

    urlOutputArea.setColumns(20);
    urlOutputArea.setEditable(false);
    urlOutputArea.setRows(5);
    jScrollPane2.setViewportView(urlOutputArea);

    activityProgressBar.setIndeterminate(true);

    menuFile.setText("File");

    menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    menuItemExit.setText("Exit");
    menuItemExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItemExitActionPerformed(evt);
      }
    });
    menuFile.add(menuItemExit);

    menuBar.add(menuFile);

    menuQuestionMark.setText("?");

    menuItemLog.setText("Log");
    menuItemLog.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItemLogActionPerformed(evt);
      }
    });
    menuQuestionMark.add(menuItemLog);

    menuItemAbout.setText("About");
    menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuItemAboutActionPerformed(evt);
      }
    });
    menuQuestionMark.add(menuItemAbout);

    menuBar.add(menuQuestionMark);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lableUser)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14)
            .addComponent(labelPassword)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(buttonSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonUpload)
                .addGap(18, 18, 18)
                .addComponent(activityProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
              .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lableUser)
          .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelPassword)
          .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(buttonSelect)
                .addComponent(buttonUpload))
              .addComponent(activityProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void buttonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectActionPerformed
    List<File> files;
    JFileChooser chooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "jpeg");
    chooser.setFileFilter(filter);
    chooser.setMultiSelectionEnabled(true);
    ImagePreviewAccessory preview = new ImagePreviewAccessory();
    chooser.setAccessory(preview);
    chooser.addPropertyChangeListener(preview);
    int returnVal = chooser.showOpenDialog(null);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      files = Arrays.asList(chooser.getSelectedFiles());
      logger.debug("Selected {} files", files.size());
    } else {
      logger.debug("No files selected");
      files = Collections.emptyList();
    }
    fileList.setModel(new FileListModel(files));
}//GEN-LAST:event_buttonSelectActionPerformed

    private void buttonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUploadActionPerformed
      if (textFieldUsername.getText().length() == 0 || textFieldPassword.getPassword().length == 0) {
        JOptionPane.showMessageDialog(this, "Please enter the login details", "Error", JOptionPane.ERROR_MESSAGE);
        return;
      }

      FileListModel list = (FileListModel) this.fileList.getModel();
      this.fileList.setModel(FileListModel.EMPTY_MODEL);

      if (list.getSize() == 0 || list.getSize() > 20) {
        JOptionPane.showMessageDialog(this, "Only 1-20 file are allowed", "Error", JOptionPane.ERROR_MESSAGE);
        return;
      }

      progressBar.setValue(0);
      progressBar.setMaximum(list.getSize());
      Uploader.this.setEnabled(false);

      SwingWorker<String, Integer> task = new BackgroundUpload(list);
      task.addPropertyChangeListener(new PropertyChangeListener() {
        @Override
        public void propertyChange(PropertyChangeEvent evt) {
          if ("progress".equals(evt.getPropertyName())) {
            progressBar.setValue((Integer) evt.getNewValue());
          }
        }
      });
      activityProgressBar.setVisible(true);
      task.execute();
}//GEN-LAST:event_buttonUploadActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
      System.exit(0);
}//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
      new AboutBox(this, true).setVisible(true);
}//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogActionPerformed
      new LogView(this, true).setVisible(true);
}//GEN-LAST:event_menuItemLogActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JProgressBar activityProgressBar;
  private javax.swing.JButton buttonSelect;
  private javax.swing.JButton buttonUpload;
  private final javax.swing.JList fileList = new javax.swing.JList();
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel labelPassword;
  private javax.swing.JLabel lableUser;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuFile;
  private javax.swing.JMenuItem menuItemAbout;
  private javax.swing.JMenuItem menuItemExit;
  private javax.swing.JMenuItem menuItemLog;
  private javax.swing.JMenu menuQuestionMark;
  private final javax.swing.JProgressBar progressBar = new javax.swing.JProgressBar();
  private final javax.swing.JPasswordField textFieldPassword = new javax.swing.JPasswordField();
  private final javax.swing.JTextField textFieldUsername = new javax.swing.JTextField();
  private final javax.swing.JTextArea urlOutputArea = new javax.swing.JTextArea();
  // End of variables declaration//GEN-END:variables

  private class BackgroundUpload extends SwingWorker<String, Integer> {
    private final FileListModel fileList;
    private final AtomicInteger uploadCount = new AtomicInteger(0);

    public BackgroundUpload(FileListModel fileList) {
      this.fileList = fileList;
    }

    @Override
    public String doInBackground() {
      final String username = textFieldUsername.getText();
      final String password = new String(textFieldPassword.getPassword());
      return new UploadBatch(username, password, new UploadBatchCallbackImpl()).upload(fileList);
    }

    @Override
    protected void done() {
      try {
        urlOutputArea.setText(get());
        activityProgressBar.setVisible(false);
      } catch (InterruptedException | ExecutionException e) {
        logger.error("Exception in Future.get()", e);
      }
      Uploader.this.setEnabled(true);
    }

    private final class UploadBatchCallbackImpl implements UploadBatchCallback {
      @Override
      public void uploaded(File uploaded) {
        setProgress(uploadCount.incrementAndGet());
      }

      @Override
      public void failed(File cur) {
        // TODO: show an error somewhere
        setProgress(uploadCount.incrementAndGet());
      }
    }
  }
}
