name: Window Installer

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  installer:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create installer
      shell: pwsh
      run: |
        $pom_xml = New-Object -TypeName XML
        $pom_xml.Load((Get-Location).tostring() + "\pom.xml")
        $full_version = $pom_xml.project.version
        if ($full_version -match "-SNAPSHOT$") {
          $version = $full_version -replace "-SNAPSHOT", ""
          $version = $version - 0.1 # use previous version as a base for snapshots
          $version = "${version}.9${env:GITHUB_RUN_NUMBER}" # make it a high value
        } else {
          $version = $full_version
        }
        .\create-windows-package.ps1 "target/fzpwuploader-${full_version}.jar" "${version}" server
    - name: Archive installer
      uses: actions/upload-artifact@v2
      with:
        name: fzpwuploader.exe
        path: ./*.exe
